DoAnAsp/Areas/Admin/Controllers/AdminModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnAsp.Areas.Admin.Data;
using DoAnAsp.Areas.Admin.Views;
using Microsoft.AspNetCore.Http;

namespace DoAnAsp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminModelsController : Controller
    {
        private readonly DPContext _context;

        public AdminModelsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminModels
        public async Task<IActionResult> Index()
        {
            try
            {
                var list = _context.admin.Where(s => s.Username == HttpContext.Session.GetString("username").ToString());
                if (list.Count() != 0)
                {
                    ViewBag.Username = HttpContext.Session.GetString("username").ToString();
                    return View(await _context.admin.ToListAsync());
                }
                else
                {
                    var url = Url.RouteUrl(new { controller = "Home", action = "Index", area = "" });
                    return Redirect(url);
                }
            }
            catch (Exception e)
            {
                var url = Url.RouteUrl(new { controller = "Login", action = "Index", area = "" });
                return Redirect(url);
            }
        }

        // GET: Admin/AdminModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adminModel = await _context.admin
                .FirstOrDefaultAsync(m => m.IdAdmin == id);
            if (adminModel == null)
            {
                return NotFound();
            }

            return View(adminModel);
        }

        // GET: Admin/AdminModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAdmin,Username,Password,Hoten,Sdt,Email")] AdminModel adminModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(adminModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(adminModel);
        }

        // GET: Admin/AdminModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adminModel = await _context.admin.FindAsync(id);
            if (adminModel == null)
            {
                return NotFound();
            }
            return View(adminModel);
        }

        // POST: Admin/AdminModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAdmin,Username,Password,Hoten,Sdt,Email")] AdminModel adminModel)
        {
            if (id != adminModel.IdAdmin)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adminModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminModelExists(adminModel.IdAdmin))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(adminModel);
        }

        // GET: Admin/AdminModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adminModel = await _context.admin
                .FirstOrDefaultAsync(m => m.IdAdmin == id);
            if (adminModel == null)
            {
                return NotFound();
            }

            return View(adminModel);
        }

        // POST: Admin/AdminModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adminModel = await _context.admin.FindAsync(id);
            _context.admin.Remove(adminModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdminModelExists(int id)
        {
            return _context.admin.Any(e => e.IdAdmin == id);
        }
    }
}

DoAnAsp/Areas/Admin/Controllers/HoaDonModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnAsp.Areas.Admin.Data;
using DoAnAsp.Areas.Admin.Models;
using Microsoft.AspNetCore.Http;

namespace DoAnAsp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HoaDonModelsController : Controller
    {
        private readonly DPContext _context;

        public HoaDonModelsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/HoaDonModels
        public async Task<IActionResult> Index()
        {
            try
            {
                var list = _context.admin.Where(s => s.Username == HttpContext.Session.GetString("username").ToString());
                if (list.Count() != 0)
                {
                    ViewBag.Username = HttpContext.Session.GetString("username").ToString();
                    return View(await _context.hoadon.ToListAsync());
                }
                else
                {
                    var url = Url.RouteUrl(new { controller = "Home", action = "Index", area = "" });
                    return Redirect(url);
                }
            }
            catch (Exception e)
            {
                var url = Url.RouteUrl(new { controller = "Login", action = "Index", area = "" });
                return Redirect(url);
            }
        }

        // GET: Admin/HoaDonModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDonModel = await _context.hoadon
                .FirstOrDefaultAsync(m => m.IdHD == id);
            if (hoaDonModel == null)
            {
                return NotFound();
            }

            return View(hoaDonModel);
        }

        // GET: Admin/HoaDonModels/Create
        public IActionResult Create()
        {
            ViewBag.IdUser = _context.user.ToList();
            return View();
        }

        // POST: Admin/HoaDonModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdHD,NgaylapHD,Thanhtien,IdUser,Diachi,Sdt,Trangthai")] HoaDonModel hoaDonModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoaDonModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hoaDonModel);
        }

        // GET: Admin/HoaDonModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDonModel = await _context.hoadon.FindAsync(id);
            if (hoaDonModel == null)
            {
                return NotFound();
            }
            return View(hoaDonModel);
        }

        // POST: Admin/HoaDonModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdHD,NgaylapHD,Thanhtien,IdUser,Diachi,Sdt,Trangthai")] HoaDonModel hoaDonModel)
        {
            if (id != hoaDonModel.IdHD)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoaDonModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoaDonModelExists(hoaDonModel.IdHD))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hoaDonModel);
        }

        // GET: Admin/HoaDonModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDonModel = await _context.hoadon
                .FirstOrDefaultAsync(m => m.IdHD == id);
            if (hoaDonModel == null)
            {
                return NotFound();
            }

            return View(hoaDonModel);
        }

        // POST: Admin/HoaDonModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoaDonModel = await _context.hoadon.FindAsync(id);
            _context.hoadon.Remove(hoaDonModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoaDonModelExists(int id)
        {
            return _context.hoadon.Any(e => e.IdHD == id);
        }
    }
}

DoAnAsp/Areas/Admin/Controllers/UserModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnAsp.Areas.Admin.Data;
using DoAnAsp.Areas.Admin.Models;
using Microsoft.AspNetCore.Http;

namespace DoAnAsp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserModelsController : Controller
    {
        private readonly DPContext _context;

        public UserModelsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/UserModels
        public async Task<IActionResult> Index()
        {
            try
            {
                var list = _context.admin.Where(s => s.Username == HttpContext.Session.GetString("username").ToString());
                if (list.Count() != 0)
                {
                    ViewBag.Username = HttpContext.Session.GetString("username").ToString();
                    return View(await _context.user.ToListAsync());
                }
                else
                {
                    var url = Url.RouteUrl(new { controller = "Home", action = "Index", area = "" });
                    return Redirect(url);
                }
            }
            catch (Exception e)
            {
                var url = Url.RouteUrl(new { controller = "Login", action = "Index", area = "" });
                return Redirect(url);
            }
        }

        // GET: Admin/UserModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userModel = await _context.user
                .FirstOrDefaultAsync(m => m.IdUser == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // GET: Admin/UserModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/UserModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUser,HotenUser,EmailUser,SdtUser,DiachiUser,UsernameUser,PasswordUser,TrangthaiUser")] UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: Admin/UserModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userModel = await _context.user.FindAsync(id);
            if (userModel == null)
            {
                return NotFound();
            }
            return View(userModel);
        }

        // POST: Admin/UserModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUser,HotenUser,EmailUser,SdtUser,DiachiUser,UsernameUser,PasswordUser,TrangthaiUser")] UserModel userModel)
        {
            if (id != userModel.IdUser)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserModelExists(userModel.IdUser))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: Admin/UserModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userModel = await _context.user
                .FirstOrDefaultAsync(m => m.IdUser == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // POST: Admin/UserModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userModel = await _context.user.FindAsync(id);
            _context.user.Remove(userModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserModelExists(int id)
        {
            return _context.user.Any(e => e.IdUser == id);
        }
    }
}

DoAnAsp/Areas/Admin/Views/Shared/_FooterPartial.cshtml
<div class="footer-copyright-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                
            </div>
        </div>
    </div>
</div>
    </div>
<!-- jquery
    ============================================ -->
<script src="~/template/admin/js/vendor/jquery-1.12.4.min.js"></script>
<!-- bootstrap JS
    ============================================ -->
<script src="~/template/admin/js/bootstrap.min.js"></script>
<!-- wow JS
    ============================================ -->
<script src="~/template/admin/js/wow.min.js"></script>
<!-- price-slider JS
    ============================================ -->
<script src="~/template/admin/js/jquery-price-slider.js"></script>
<!-- meanmenu JS
    ============================================ -->
<script src="~/template/admin/js/jquery.meanmenu.js"></script>
<!-- owl.carousel JS
    ============================================ -->
<script src="~/template/admin/js/owl.carousel.min.js"></script>
<!-- sticky JS
    ============================================ -->
<script src="~/template/admin/js/jquery.sticky.js"></script>
<!-- scrollUp JS
    ============================================ -->
<script src="~/template/admin/js/jquery.scrollUp.min.js"></script>
<!-- mCustomScrollbar JS
    ============================================ -->
<script src="~/template/admin/js/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/template/admin/js/scrollbar/mCustomScrollbar-active.js"></script>
<!-- metisMenu JS
    ============================================ -->
<script src="~/template/admin/js/metisMenu/metisMenu.min.js"></script>
<script src="~/template/admin/js/metisMenu/metisMenu-active.js"></script>
<!-- sparkline JS
    ============================================ -->
<script src="~/template/admin/js/sparkline/jquery.sparkline.min.js"></script>
<script src="~/template/admin/js/sparkline/jquery.charts-sparkline.js"></script>
<!-- calendar JS
    ============================================ -->
<script src="~/template/admin/js/calendar/moment.min.js"></script>
<script src="~/template/admin/js/calendar/fullcalendar.min.js"></script>
<script src="~/template/admin/js/calendar/fullcalendar-active.js"></script>
<!-- float JS
    ============================================ -->
<script src="~/template/admin/js/flot/jquery.flot.js"></script>
<script src="~/template/admin/js/flot/jquery.flot.resize.js"></script>
<script src="~/template/admin/js/flot/curvedLines.js"></script>
<script src="~/template/admin/js/flot/flot-active.js"></script>
<!-- plugins JS
    ============================================ -->
<script src="~/template/admin/js/plugins.js"></script>
<!-- main JS
    ============================================ -->
<script src="~/template/admin/js/main.js"></script>

DoAnAsp/Areas/Admin/Views/Shared/_HeadPartial.cshtml
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>Dashboard V.1 | Nalika - Material Admin Template</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- favicon
    ============================================ -->
<link rel="shortcut icon" type="image/x-icon" href="~/template/admin/img/favicon.ico">
<!-- Google Fonts
    ============================================ -->
<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
<!-- Bootstrap CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/bootstrap.min.css">
<!-- Bootstrap CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/font-awesome.min.css">
<!-- nalika Icon CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/nalika-icon.css">
<!-- owl.carousel CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/owl.carousel.css">
<link rel="stylesheet" href="~/template/admin/css/owl.theme.css">
<link rel="stylesheet" href="~/template/admin/css/owl.transitions.css">
<!-- animate CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/animate.css">
<!-- normalize CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/normalize.css">
<!-- meanmenu icon CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/meanmenu.min.css">
<!-- main CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/main.css">
<!-- morrisjs CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/morrisjs/morris.css">
<!-- mCustomScrollbar CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/scrollbar/jquery.mCustomScrollbar.min.css">
<!-- metisMenu CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/metisMenu/metisMenu.min.css">
<link rel="stylesheet" href="~/template/admin/css/metisMenu/metisMenu-vertical.css">
<!-- calendar CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/calendar/fullcalendar.min.css">
<link rel="stylesheet" href="~/template/admin/css/calendar/fullcalendar.print.min.css">
<!-- style CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/style.css">
<!-- responsive CSS
    ============================================ -->
<link rel="stylesheet" href="~/template/admin/css/responsive.css">

<!--font tieng viet-->
<!-- modernizr JS
    ============================================ -->
<script src="~/template/admin/js/vendor/modernizr-2.8.3.min.js"></script>

DoAnAsp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("_HeadPartial.cshtml")
    @RenderSection("css", required: false)
</head>
<body>
    @await Html.PartialAsync("_MenuPartial.cshtml")
    @await Html.PartialAsync("_HeaderPartial.cshtml")
    @RenderBody()
    <!-- Modal -->
    <div class="modal fade" id="form-modal" role="dialog" >
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content" style="background-color:#1b2a47">
                <div class="modal-header">
                    <div style="display:flex;justify-content:space-between">
                        <h4 class="modal-title" style="color:black">Thông báo</h4>
                        <button type="button" class="close" data-dismiss="modal" style="background-color:#00ffff;width:50px;border-radius:6px">&times;</button>
                    </div>
                </div>
                <div class="modal-body">
                    <p style="color:#ef592d">Chào mừng bạn đến trang quản lý Bình Luận</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" style="background-color:#4caf50">Đóng</button>
                </div>
            </div>

        </div>
    </div>
    @section Scripts{
        <script>
            $(document).ready(function () {
                $('#myModal').modal('show');
            })
        </script>
    }
    @await Html.PartialAsync("_FooterPartial.cshtml")
    <script>
        showModal = (url, title) => {
            $.ajax({
                type: "GET",
                url: url,
                success: function (res) {
                    // Hiễn thị form create edit
                    $('#form-modal .modal-body').html(res);
                    //hiện tiêu đề
                    $('#form-modal .modal-title').html(title);
                    //hiện modal
                    $('#form-modal').modal('show');
                }
            })
        }
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DoAnAsp/Areas/Admin/Views/Shared/_MenuPartial.cshtml
<div class="left-sidebar-pro">
    <nav id="sidebar" class="">
        <div class="sidebar-header">

            <strong><img src="~/template/admin/img/logo/logosn.png" alt="" /></strong>
        </div>
        <div class="nalika-profile">
            <div class="profile-dtl">
                <a href="#"><img src="~/template/admin/img/notification/4.jpg" alt="" /></a>
                <h2>Lakian <span class="min-dtn">Das</span></h2>
            </div>
            <div class="profile-social-dtl">
                <ul class="dtl-social">
                    <li><a href="#"><i class="icon nalika-facebook"></i></a></li>
                    <li><a href="#"><i class="icon nalika-twitter"></i></a></li>
                    <li><a href="#"><i class="icon nalika-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="left-custom-menu-adp-wrap comment-scrollbar">
            <nav class="sidebar-nav left-sidebar-menu-pro">
                <ul class="metismenu" id="menu1">
                    <li class="active">
                        <a asp-action="Index" asp-controller="AdminModels">
                            <span>Tài khoản Admin</span>
                        </a>
                        <a asp-action="Index" asp-controller="BinhLuanModels">
                            <span>Bình luận</span>
                        </a>
                        <a asp-action="Index" asp-controller="ChiTietHoaDonModels">
                            <span>Chi tiết hóa đơn</span>
                        </a>
                        <a asp-action="Index" asp-controller="HoaDonModels">
                            <span>Hóa đơn</span>
                        </a>
                        <a asp-action="Index" asp-controller="LoaiSPModelcs">
                            <span>Loại sản phẩm</span>
                        </a>
                        <a asp-action="Index" asp-controller="NhaCungCapModels">
                            <span>Nhà cung cấp</span>
                        </a>
                        <a asp-action="Index" asp-controller="SanPhamModels">
                            <span>Sản phẩm</span>
                        </a>
                        <a asp-action="Index" asp-controller="UserModels">
                            <span>Tài khoản khách hàng</span>
                        </a>
                    </li>
                    
                </ul>
            </nav>
        </div>
    </nav>
</div>