DoAnAsp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DoAnAsp.Models;
using System.Diagnostics;

namespace DoAnAsp.Controllers
{
    public class BlogController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DoAnAsp/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DoAnAsp.Models;
using System.Diagnostics;

namespace DoAnAsp.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DoAnAsp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DoAnAsp.Models;
using System.Diagnostics;

namespace DoAnAsp.Controllers
{
    public class ContactController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DoAnAsp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DoAnAsp.Models;
using System.Diagnostics;
using DoAnAsp.Areas.Admin.Data;
using Microsoft.AspNetCore.Http;

namespace DoAnAsp.Controllers
{
    public class LoginController : Controller
    {
        private readonly DPContext _context;

        public LoginController(DPContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult login(string UsernameUser, string PasswordUser)
        {
            var user = _context.user.Where(s => s.UsernameUser == UsernameUser).ToList();
            var admin = _context.admin.Where(s => s.Username == UsernameUser).ToList();
            if (user.Count != 0)
            {
                if (user[0].PasswordUser == PasswordUser)
                {
                    HttpContext.Session.SetString("username", user[0].UsernameUser);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                if (admin.Count != 0)
                {
                    if (admin[0].Password == PasswordUser)
                    {
                        HttpContext.Session.SetString("username", admin[0].Username);
                        var url = Url.RouteUrl("areas", new { controller = "SanPhamModels", action = "Index", area = "Admin" });
                        return Redirect(url);
                    }
                    else
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
        }
    }
}

DoAnAsp/Views/Shared/_FooterPartial.cshtml
 <!--::footer_part start::-->
<footer class="footer_part">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-sm-6 col-lg-2">
                <div class="single_footer_part">
                    <h4>Category</h4>
                    <ul class="list-unstyled">
                        <li><a href="#">Male</a></li>
                        <li><a href="#">Female</a></li>
                        <li><a href="#">Shoes</a></li>
                        <li><a href="#">Fashion</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-2">
                <div class="single_footer_part">
                    <h4>Company</h4>
                    <ul class="list-unstyled">
                        <li><a href="">About</a></li>
                        <li><a href="">News</a></li>
                        <li><a href="">FAQ</a></li>
                        <li><a href="">Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="single_footer_part">
                    <h4>Address</h4>
                    <ul class="list-unstyled">
                        <li><a href="#">200, Green block, NewYork</a></li>
                        <li><a href="#">0367200410</a></li>
                        <li><span>tannhat.21012000@gmail.com</span></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4">
                <div class="single_footer_part">
                    <h4>Newsletter</h4>
                    <div id="mc_embed_signup">
                        <form target="_blank"
                              action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="subscribe_form relative mail_part">
                            <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                   class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = ' Email Address '">
                            <button type="submit" name="submit" id="newsletter-submit"
                                    class="email_icon newsletter-submit button-contactForm">
                                subscribe
                            </button>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                    <div class="social_icon">
                        <a href="#"><i class="ti-facebook"></i></a>
                        <a href="#"><i class="ti-twitter-alt"></i></a>
                        <a href="#"><i class="ti-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="copyright_text">
                    <P>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </P>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--::footer_part end::-->
<!-- jquery plugins here-->
<script src="~/template/user/js/jquery-1.12.1.min.js"></script>
<!-- popper js -->
<script src="~/template/user/js/popper.min.js"></script>
<!-- bootstrap js -->
<script src="~/template/user/js/bootstrap.min.js"></script>
<!-- easing js -->
<script src="~/template/user/js/jquery.magnific-popup.js"></script>
<!-- swiper js -->
<script src="~/template/user/js/swiper.min.js"></script>
<!-- swiper js -->
<script src="~/template/user/js/mixitup.min.js"></script>
<!-- particles js -->
<script src="~/template/user/js/owl.carousel.min.js"></script>
<script src="~/template/user/js/jquery.nice-select.min.js"></script>
<!-- slick js -->
<script src="~/template/user/js/slick.min.js"></script>
<script src="~/template/user/js/jquery.counterup.min.js"></script>
<script src="~/template/user/js/waypoints.min.js"></script>
<script src="~/template/user/js/contact.js"></script>
<script src="~/template/user/js/jquery.ajaxchimp.min.js"></script>
<script src="~/template/user/js/jquery.form.js"></script>
<script src="~/template/user/js/jquery.validate.min.js"></script>
<script src="~/template/user/js/mail-script.js"></script>
<!-- custom js -->
<script src="~/template/user/js/custom.js"></script>

DoAnAsp/Views/Shared/_HeadPartial.cshtml
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>winter</title>
<link rel="icon" href="img/favicon.png">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="~/template/user/css/bootstrap.min.css">
<!-- animate CSS -->
<link rel="stylesheet" href="~/template/user/css/animate.css">
<!-- owl carousel CSS -->
<link rel="stylesheet" href="~/template/user/css/owl.carousel.min.css">
<!-- font awesome CSS -->
<link rel="stylesheet" href="~/template/user/css/all.css">
<!-- flaticon CSS -->
<link rel="stylesheet" href="~/template/user/css/flaticon.css">
<link rel="stylesheet" href="~/template/user/css/themify-icons.css">
<!-- font awesome CSS -->
<link rel="stylesheet" href="~/template/user/css/magnific-popup.css">
<!-- swiper CSS -->
<link rel="stylesheet" href="~/template/user/css/slick.css">
<!-- style CSS -->
<link rel="stylesheet" href="~/template/user/css/style.css">

DoAnAsp/Views/Shared/_HeaderPartial.cshtml
<!--::header part start::-->
<header class="main_menu home_menu">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-center">
            <div class="col-lg-11">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href="index.html"> <img src="~/template/user/img/logo.png" alt="logo"> </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_icon"><i class="fas fa-bars"></i></span>
                    </button>

                    <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Shop
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category"> shop category</a>


                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_3"
                                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    pages
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Login">
                                        login

                                    </a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="UserModels" asp-action="Create">Đăng ký</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Checkout">product checkout</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Cart">shopping cart</a>

                                    <a class="dropdown-item" asp-action="Index" asp-controller="Singleproduct">Single Product</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown_2"
                                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    blog
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Blog"> blog</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Contact">Contact</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <p class="nav-link">@ViewBag.user</p>
                            </li>

                   
                        </ul>
                    </div>
                    <div class="hearer_icon d-flex">
                        <div class="dropdown cart">
                            <a class="dropdown-toggle" href="#" id="navbarDropdown3" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="ti-bag"></i>
                            </a>
                            <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <div class="single_product">

                                </div>
                            </div> -->
                        </div>
                        <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div class="search_input" id="search_input_box">
        <div class="container ">
            <form class="d-flex justify-content-between search-inner">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="ti-close" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>
<!-- Header part end-->

DoAnAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @await Html.PartialAsync("_HeadPartial.cshtml")
    @RenderSection("css", required: false)
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial.cshtml")
    @RenderBody()
    @await Html.PartialAsync("_FooterPartial.cshtml")
    @RenderSection("Scripts", required: false)
</body>
</html>