DoAnAsp/Areas/Admin/Models/SanPhamModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DoAnAsp.Areas.Admin.Models
{
    public class SanPhamModel
    {
        [Key]
        public int IdSP { get; set; }
        [Required]
        [StringLength(100)]
        public string TenSP { get; set; }
        public string Anh { get; set; }
        public double Gia { get; set; }
        [StringLength(20)]
        public string Donvitinh { get; set; }
        [Required]
        public int Soluongton { get; set; }
        public int IdNCC { get; set; }
        [ForeignKey("IdNCC")]
        public virtual NhaCungCapModel nhacungcap { get; set; }
        public int IdLSP { get; set; }
        [ForeignKey("IdLSP")]
        public virtual LoaiSPModelcs loaisp { get; set; }
        public string Mota { get; set; }
        public bool Trangthai { get; set; }
        public ICollection<BinhLuanModel> binhluan { get; set; }
        
        
    }
}

DoAnAsp/Areas/Admin/Controllers/SanPhamModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnAsp.Areas.Admin.Data;
using DoAnAsp.Areas.Admin.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace DoAnAsp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SanPhamModelsController : Controller
    {
        private readonly DPContext _context;

        public SanPhamModelsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/SanPhamModels
        public async Task<IActionResult> Index()
        {
            
            try
            {
                var list = _context.admin.Where(s => s.Username == HttpContext.Session.GetString("username").ToString());
                if (list.Count() != 0)
                {
                    ViewBag.Username = HttpContext.Session.GetString("username").ToString();
                    return View(await _context.sanpham.Include(i => i.nhacungcap).Include(h => h.loaisp).ToListAsync());
                }
                else
                {
                    var url = Url.RouteUrl(new { controller = "Home", action = "Index", area = "" });
                    return Redirect(url);
                }
            }
            catch (Exception e)
            {
                var url = Url.RouteUrl(new { controller = "Login", action = "Index", area = "" });
                return Redirect(url);
            }
        }

        // GET: Admin/SanPhamModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPhamModel = await _context.sanpham
                .FirstOrDefaultAsync(m => m.IdSP == id);
            if (sanPhamModel == null)
            {
                return NotFound();
            }

            return View(sanPhamModel);
        }

        // GET: Admin/SanPhamModels/Create
        public IActionResult Create()
        {
            ViewBag.IdNCC = _context.nhacungcap.ToList();
            ViewBag.IdLSP = _context.loaisanpham.ToList();
            return View();
        }

        // POST: Admin/SanPhamModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdSP,TenSP,Anh,Gia,Donvitinh,Soluongton,IdNCC,IdLSP,Mota,Trangthai")] SanPhamModel sanPhamModel, IFormFile ful)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanPhamModel);
                await _context.SaveChangesAsync();
                var parth = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/template/admin/img",
                    sanPhamModel.IdSP + "." + ful.FileName.Split(".")
                    [ful.FileName.Split(".").Length - 1]);
                using (var stream = new FileStream(parth, FileMode.Create))
                {
                    await ful.CopyToAsync(stream);
                }
                sanPhamModel.Anh = sanPhamModel.IdSP + "." + ful.FileName.Split(".")
                    [ful.FileName.Split(".").Length - 1];
                _context.Update(sanPhamModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.IdNCC = _context.nhacungcap.ToList();
            ViewBag.IdLSP = _context.loaisanpham.ToList();
            return View(sanPhamModel);
        }

        // GET: Admin/SanPhamModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPhamModel = await _context.sanpham.FindAsync(id);
            if (sanPhamModel == null)
            {
                return NotFound();
            }
            ViewBag.IdNCC = _context.nhacungcap.ToList();
            ViewBag.IdLSP = _context.loaisanpham.ToList();
            return View(sanPhamModel);
        }

        // POST: Admin/SanPhamModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdSP,TenSP,Anh,Gia,Donvitinh,Soluongton,IdNCC,IdLSP,Mota,Trangthai")] SanPhamModel sanPhamModel, IFormFile ful, string HinhAnh)
        {
            if (id != sanPhamModel.IdSP)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    var parth = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/template/admin/img", HinhAnh);
                    System.IO.File.Delete(parth);
                    if(ful == null)
                    {
                        sanPhamModel.Anh = HinhAnh;
                    }
                    else
                    {
                        parth = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/template/admin/img", sanPhamModel.IdSP + "." + ful.FileName.Split(".")
                        [ful.FileName.Split(".").Length - 1]);
                        using (var stream = new FileStream(parth, FileMode.Create))
                        {
                            await ful.CopyToAsync(stream);
                        }
                        sanPhamModel.Anh = sanPhamModel.IdSP + "." + ful.FileName.Split(".")
                            [ful.FileName.Split(".").Length - 1];
                    }
                    
                    _context.Update(sanPhamModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamModelExists(sanPhamModel.IdSP))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(sanPhamModel);
        }

        // GET: Admin/SanPhamModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPhamModel = await _context.sanpham
                .FirstOrDefaultAsync(m => m.IdSP == id);
            if (sanPhamModel == null)
            {
                return NotFound();
            }

            return View(sanPhamModel);
        }

        // POST: Admin/SanPhamModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPhamModel = await _context.sanpham.FindAsync(id);
            _context.sanpham.Remove(sanPhamModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamModelExists(int id)
        {
            return _context.sanpham.Any(e => e.IdSP == id);
        }
    }
}

DoAnAsp/Areas/Admin/Views/SanPhamModels/Create.cshtml
@model DoAnAsp.Areas.Admin.Models.SanPhamModel

@{
    ViewData["Title"] = "Create";
    Layout = null;
}
@using (Html.BeginForm("Create", "SanPhamModels", FormMethod.Post, new { enctype = "multipart/form-data" })) ;


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" style="color: white; padding-left:20px;" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenSP" class="control-label"></label>
                <input asp-for="TenSP" class="form-control" style="border: solid 1px white;" />
                <span asp-validation-for="TenSP" class="text-danger"></span>
            </div>
            <div class="custom-file">
                <label asp-for="Anh" for="ful" class="custom-file-label">Choose Image</label>
                <input type="file" name="ful" id="ful" class="custom-file-input" style="border: solid 1px white;" />
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" style="border: solid 1px white;" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Donvitinh" class="control-label"></label>
                <input asp-for="Donvitinh" class="form-control" style="border: solid 1px white;" />
                <span asp-validation-for="Donvitinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soluongton" class="control-label"></label>
                <input asp-for="Soluongton" class="form-control" style="border: solid 1px white;" />
                <span asp-validation-for="Soluongton" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNCC" class="control-label"></label>
                <select asp-for="IdNCC" class="form-control" asp-items="@(new SelectList(ViewBag.IdNCC,"IdNCC","TenNCC"))" style="border: solid 1px white;"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdLSP" class="control-label"></label>
                <select asp-for="IdLSP" class="form-control" asp-items="@(new SelectList(ViewBag.IdLSP,"IdLSP","TenLSP"))" style="border: solid 1px white;"></select>
            </div>
            <div class="form-group">
                <label asp-for="Mota" class="control-label"></label>
                <input asp-for="Mota" class="form-control" style="border: solid 1px white;" />
                <span asp-validation-for="Mota" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Trangthai" style="border: solid 1px white;" /> @Html.DisplayNameFor(model => model.Trangthai)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" style="background-color:aqua; color:black; font-size:20px;" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoAnAsp/Areas/Admin/Views/SanPhamModels/Delete.cshtml
@model DoAnAsp.Areas.Admin.Models.SanPhamModel

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}


<h3 style="color: white; padding-left:20px;">Are you sure you want to delete this?</h3>
<div>
    <h4 style="color: white; padding-left:20px;">SanPhamModel</h4>
    <hr />
    <dl class="row" style="color: white; padding-left:20px;">
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.TenSP)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.Anh)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.Anh)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.Donvitinh)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.Donvitinh)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.Soluongton)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.Soluongton)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.IdNCC)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.IdNCC)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.IdLSP)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.IdLSP)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.Mota)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.Mota)
        </dd>
        <dt class = "col-sm-2" style="border: solid 1px white;">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class = "col-sm-10" style="border: solid 1px white;">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
    </dl>
    
    <form asp-action="Delete" style="color: white; padding-left:20px;">
        <input type="hidden" asp-for="IdSP" style="border: solid 1px white;"/>
        <input type="submit" value="Delete" class="btn btn-danger" style="border: solid 1px white;"/> 
        
    </form>
</div>

DoAnAsp/Areas/Admin/Views/SanPhamModels/Details.cshtml
@model DoAnAsp.Areas.Admin.Models.SanPhamModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SanPhamModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Donvitinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Donvitinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Soluongton)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Soluongton)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNCC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNCC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdLSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdLSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdSP">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DoAnAsp/Areas/Admin/Views/SanPhamModels/Edit.cshtml
@model DoAnAsp.Areas.Admin.Models.SanPhamModel

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" style="color: white; padding-left:20px;" enctype="multipart/form-data" method="post"v>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdSP" style="border: solid 1px white;"/>
            <div class="form-group">
                <label asp-for="TenSP" class="control-label"></label>
                <input asp-for="TenSP" class="form-control" style="border: solid 1px white;"/>
                <span asp-validation-for="TenSP" class="text-danger"></span>
            </div>
            <div class="custom-file">
                <label asp-for="Anh" for="ful" class="custom-file-label">Choose Image</label>
                <input type="file" name="ful" id="ful" class="custom-file-input" style="border: solid 1px white;" />
                <input type="hidden" name="HinhAnh" value="@Model.Anh" />
                <span asp-validation-for="Anh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" style="border: solid 1px white;"/>
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Donvitinh" class="control-label"></label>
                <input asp-for="Donvitinh" class="form-control" style="border: solid 1px white;"/>
                <span asp-validation-for="Donvitinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soluongton" class="control-label"></label>
                <input asp-for="Soluongton" class="form-control" style="border: solid 1px white;"/>
                <span asp-validation-for="Soluongton" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNCC" class="control-label"></label>
                <select asp-for="IdNCC" class="form-control" asp-items="@(new SelectList(ViewBag.IdNCC,"IdNCC","TenNCC"))" style="border: solid 1px white;"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdLSP" class="control-label"></label>
                <select asp-for="IdLSP" class="form-control" asp-items="@(new SelectList(ViewBag.IdLSP,"IdLSP","TenLSP"))" style="border: solid 1px white;"></select>
            </div>
            <div class="form-group">
                <label asp-for="Mota" class="control-label"></label>
                <input asp-for="Mota" class="form-control" style="border: solid 1px white;"/>
                <span asp-validation-for="Mota" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Trangthai" style="border: solid 1px white;"/> @Html.DisplayNameFor(model => model.Trangthai)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" style="background-color:aqua; color:black; font-size:20px;"/>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoAnAsp/Areas/Admin/Views/SanPhamModels/Index.cshtml
@model IEnumerable<DoAnAsp.Areas.Admin.Models.SanPhamModel>

@{
    ViewData["Title"] = "Index";
}
<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>Products List</h4>
                    <div class="col-lg-6 col-md-7 col-sm-6 col-xs-12">
                        <div class="header-top-menu tabl-d-n hd-search-rp">
                            <div class="breadcome-heading">
                                <input type="text" placeholder="Search..." class="form-control" id="keyword" style="color: white">
                                <a id="chon"><i class="fa fa-search"></i></a>

                                
                            </div>
                        </div>
                    </div>
                    <div class="add-product">
                        <a onclick="showModal('@Url.Action("Create","SanPhamModels",null,Context.Request.Scheme)','Thêm sản phẩm')" style="background-color:aqua; color:black; font-size:20px; margin-top: -10px;"><b>Add User</b></a>
                    </div>
                    <table>
                        <thead>
                            <tr>
                                <th>Tên sản phẩm</th>
                                <th>Ảnh</th>
                                <th>Giá</th>
                                <th>Đơn vị tính</th>
                                <th>Số lượng tồn kho</th>
                                <th>Nhà cung cấp</th>
                                <th>Loại sản phẩm</th>
                                <th>Mô tả</th>
                                <th>Trạng thái</th>
                                <th>Chức năng</th>
                            </tr>
                        </thead>
                        <tbody id="ketqua">

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TenSP)
                                    </td>
                                    <td>
                                        <img src="~/template/admin/img/@Html.DisplayFor(modelItem => item.Anh)" alt="Anh" />

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Gia)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Donvitinh)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Soluongton)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.nhacungcap.TenNCC)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.nhacungcap.TenNCC)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Mota)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Trangthai)
                                    </td>
                                    <td>
                                        <a onclick="showModal('@Url.Action("Edit","SanPhamModels",new {id=$"{item.IdSP}"},Context.Request.Scheme)','Cập nhật sản phẩm')" data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                        <a onclick="showModal('@Url.Action("Delete","SanPhamModels",new {id=$"{item.IdSP}"},Context.Request.Scheme)','Xóa sản phẩm')" data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                    @section Scripts {
                        <script>
                            $(document).ready(function () {
                                $("#chon").click(function () {
                                    $.ajax({
                                        method: "GET",
                                        url: "../../api/SanPhamModels/GETdata",
                                        data: { 'keyword': $("#keyword").val() }
                                    }).done(function (data) {

                                        var dataJS = JSON.parse(data);
                                        console.log(dataJS);
                                        var i = '';
                                        $.each(dataJS, function (index, value) {
                                            var status = '';
                                            if (value.Trangthai) {
                                                status = 'checked'
                                            }
                                            i += ` <tr>
                                                                                <td>
                                                                                   ${value.TenSP}
                                                                                </td>
                                                                                <td>
                                                                                    <img src="/template/admin/img/${value.Anh}" alt="Anh" />

                                                                                </td>
                                                                                <td>
                                                                                    ${value.Gia}
                                                                                </td>
                                                                                <td>
                                                                                  ${value.Donvitinh}
                                                                                </td>
                                                                                <td>
                                                                                    ${value.Soluongton}
                                                                                </td>
                                                                                <td>
                                                                                   ${value.IdNCC}
                                                                                </td>
                                                                                <td>
                                                                                   ${value.IdLSP}
                                                                                </td>
                                                                                <td>
                                                                                    ${value.Mota}
                                                                                </td>
                                                                                <td>
                                                                                        <input type="checkbox" ${status} disabled>
                                                                                   </td>
                                                                                <td>
                                                                                    <a href="/admin/SanPhamModels/Edit/`+ value.IdSP + `" data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

                                                                                    <a href="/admin/SanPhamModels/Delete/`+ value.IdSP + `" data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                                                                    </td>
                                                                                </tr>`
                                        });
                                        //console.log('i nè ' + i);
                                        $('#ketqua').html(i);
                                    })
                                });
                            });

                        </script>
                    }
                    